image: maven:3.3-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s config/gitlab-ci/settings.xml --batch-mode"

before_script:
  # modify settings.xml
  - sed -i 's,ARTIFACTORY_URL,'"$ARTIFACTORY_URL"',g' config/gitlab-ci/settings.xml
  - sed -i 's,ARTIFACTORY_USER,'"$ARTIFACTORY_USER"',g' config/gitlab-ci/settings.xml
  - sed -i 's,ARTIFACTORY_PASS,'"$ARTIFACTORY_PASS"',g' config/gitlab-ci/settings.xml
  - export SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c 1-8)
  - export DATE=$(date +"%y%m%d")
  - export TAG=${DATE}.${SHORT_SHA}

stages:
 - compile
 - test
 - deploy

maven_compile:
  stage: compile
  tags:
    - maven
  script:
    - mvn compile
 
maven test:
  stage: test
  tags: 
    - maven
  script:
    - mvn test

maven_deploy2:
  image: maven:3.6.0-jdk-8-alpine
  stage: deploy
  script: 
    - mvn $MAVEN_CLI_OPTS clean deploy


maven_deploy:
  stage: deploy
  tags:
    - maven
    - artifactory
  before_script:
    #SSH agent
    - 'which ssh-agent || ( apk update  && apk add openssh)'
    - eval $(ssh-agent -s)    
    - ssh-add <(echo "$SSH_PRIVATE_KEY")    
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    #GPG (gnupg)
    - 'which gpg-agent || ( apk update  && apk add gnupg)'
    - gpg -v --batch --import <(echo "$GPG_PRIVATE_KEY")
    # Install JFrog CLI / configure artifactory
    -  curl -fL https://getcli.jfrog.io | sh
    - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
    - ./jfrog rt c show
    - export M2_HOME=/usr/share/maven
    - sed -i 's,SNAPSHOT_REPO_KEY,'"$SNAPSHOT_REPO_KEY"',g' configuration.yml
    - sed -i 's,RELEASE_REPO_KEY,'"$RELEASE_REPO_KEY"',g' configuration.yml
    - sed -i 's,ARTIFACTORY_JCENTER_REPO_KEY,'"$ARTIFACTORY_JCENTER_REPO_KEY"',g' configuration.yml
  script:
    - ./jfrog rt mvn "clean verify gpg:sign install -DadditionalJOption=-Xdoclint:none" configuration.yml --build-name=biocomponents_gitlabci_build --build-number=$CI_JOB_ID
    - ./jfrog rt bce biocomponents_gitlabci_build $CI_JOB_ID
    - ./jfrog rt bp biocomponents_gitlabci_build $CI_JOB_ID
  only:
    - master
